flomesh-io/fgw

pjs/common/health-check.js, pjs/http/forward.js, pjs/main.js, pjs/samples/health-check/config.json, pjs/tcp/forward.js, pjs/tls/forward.js, tests/shpec/pjs/common/health-check.js, tests/shpec/pjs/http/forward.js, tests/shpec/pjs/main.js, tests/shpec/pjs/samples/health-check/config.json, tests/shpec/pjs/tcp/forward.js, tests/shpec/pjs/tls/forward.js
1、HTTP负载均衡增加health check检测 
2、TCP负载均衡增加health check检测
=> 1、HTTP负载均衡增加health check检测 2、TCP负载均衡增加health check检测

demo/load-balancer/README.md
=> Update demo README.md

demo/consumer-variables/config.json, docs/README.md, pjs/filter/header-modifier.js, pjs/filter/url-rewrite.js, pjs/http/auth.js, pjs/http/codec.js, pjs/static/www1/app1/index.html, pjs/static/www1/app2/index.html, pjs/static/www2/app1/index.html, pjs/static/www2/app2/index.html, tests/shpec/pjs/filter/header-modifier.js, tests/shpec/pjs/filter/url-rewrite.js, tests/shpec/pjs/http/auth.js, tests/shpec/pjs/http/codec.js, tests/shpec/pjs/static/www1/app1/index.html, tests/shpec/pjs/static/www1/app2/index.html, tests/shpec/pjs/static/www2/app1/index.html, tests/shpec/pjs/static/www2/app2/index.html
支持在 http filter里面使用 __consumer, __http 变量
=> 支持在 http filter里面使用 __consumer, __http 变量

pjs/http/throttle-domain.js, pjs/http/throttle-route.js, tests/shpec/pjs/http/throttle-domain.js, tests/shpec/pjs/http/throttle-route.js
=> [fix] 修改限流模块计数器工作方式

demo/consumer-variables/config.json, pjs/config.json, pjs/plugins/cors.js, tests/shpec/pjs/config.json, tests/shpec/pjs/plugins/cors.js
=> 增加跨域资源共享插件cors.js

pjs/http/auth.js
=> [fix] http/auth.js的开关配置项

pjs/config.json, pjs/server/web-server.js
静态web-server 增加了2个配置项 Index、TryFiles
=> 静态web-server 增加了2个配置项 Index、TryFiles

pjs/templates/pj-auth.js
增加类似OpenAPI认证的参考实现 pjs/templates/pj-auth.js
=> 增加类似OpenAPI认证的参考实现 pj-auth.js

pjs/http/route.js
=> 优化 http/route.js，使用多级 cache

pjs/http/service.js, pjs/samples/basic-auth/config.json
auth.js 支持Basic认证，参考 samples/basic-auth/config.json
=> auth.js 支持Basic认证，参考 samples/basic-auth/config.json

pjs/http/forward.js, pjs/http/sr-auth.js, pjs/lib/connect-tcp.js
在 Configs 配置块增加配置项 ShowUpstreamStatusInResponseHeader，用于记录上游http状态
=> 在 Configs 配置块增加配置项 ShowUpstreamStatusInResponseHeader，用于记录上游http状态

pjs/config.json, pjs/http/circuit-breaker.js, pjs/http/forward.js, pjs/static/www2/index.html, tests/shpec/config/circuit-breaker_shpec/config.json
将熔断的配置从ConnectionSettings.http.CircuitBreaking简化为CircuitBreaking
=> 将熔断的配置从ConnectionSettings.http.CircuitBreaking简化为CircuitBreaking

pjs/http/forward.js, pjs/lib/utils.js, pjs/plugins/traffic-mirror.js
优化uuid转uint63的实现方式（使用Int对象代替js代码）
=> 优化uuid转uint63的实现方式（使用Int对象代替js代码）

pjs/http/codec.js, pjs/http/metrics.js, pjs/lib/metrics.js
=> 整理（新增、删除）metrics指标

pjs/common/health-check.js, pjs/config.json, pjs/http/forward.js, pjs/lib/connect-tcp.js, pjs/lib/metrics.js, pjs/tcp/forward.js
支持LeastWorkLoadBalancer等其他负载均衡算法
=> 支持LeastWorkLoadBalancer等其他负载均衡算法

pjs/config.json, pjs/http/access-control-domain.js, pjs/http/access-control-route.js, pjs/http/forward.js, pjs/lib/metrics.js, pjs/tcp/forward.js
增加LeastConnectionLoadBalancer负载均衡策略（config.json里面配置使用）
=> 增加LeastConnectionLoadBalancer负载均衡策略（config.json里面配置使用）

pjs/config.js, pjs/lib/connect-tcp.js, pjs/main.js, tests/shpec/config/health-check_shpec/config.json
增加SocketTimeout全局参数设置网络（connect/listen）各项超时（单位：秒）
=> 增加SocketTimeout全局参数设置网络（connect/listen）各项超时（单位：秒）

pjs/http/forward.js
使用ip地址作为HashingLoadBalancer的hash key
=> 使用ip地址作为HashingLoadBalancer的hash key

.github/workflows/build-latest-image.yaml, pjs/main.js
增加了全局配置项PidFile,用于保存pipy的进程id，比如："PidFile": "/tmp/pipy.pid"
=> 增加了全局配置项PidFile,用于保存pipy的进程id

pjs/lib/metrics.js, pjs/main.js, pjs/server/web-server.js
1、增加fgw_meta_info指标 2、使用http.Directory重写了web-server.js
=> 1、增加fgw_meta_info指标 2、使用http.Directory重写了web-server.js

pjs/common/health-check.js, pjs/common/resource-usage.js, pjs/config.json, pjs/lib/metrics.js, pjs/main.js
Added metric "fgw_resource_usage" to record cpu and mem usage.（only works on linux）
=> Added metric "fgw_resource_usage" to record cpu and mem usage.

pjs/common/health-check.js, pjs/common/resource-usage.js, pjs/config.json, pjs/lib/metrics.js
Health check logs and resource usage can be saved to REST server by configuration
=> Health check logs and resource usage can be saved to REST server by configuration

pjs/config.json
Delete test configuration items.
=> Delete test configuration items.

pjs/filter/header-modifier.js, pjs/filter/request-redirect.js, tests/shpec/config/circuit-breaker_shpec/config.json, tests/shpec/config/consumer-variables_shpec/config.json, tests/shpec/config/grpc-route_shpec/config.json, tests/shpec/config/header-modifier_shpec/config.json, tests/shpec/config/http-route_shpec/config.json, tests/shpec/config/https-passthrough_shpec/config.json, tests/shpec/config/load-balancing_shpec/config.json, tests/shpec/config/metrics-tracing-logging_shpec/config.json, tests/shpec/config/mtls-client_shpec/config.json, tests/shpec/config/mtls-upstream_shpec/config.json, tests/shpec/config/request-redirect_shpec/config.json, tests/shpec/config/retry_shpec/config.json, tests/shpec/config/tcp-route_shpec/config.json, tests/shpec/config/throttle-domain_shpec/config.json, tests/shpec/config/throttle-route_shpec/config.json, tests/shpec/config/tls-sni_shpec/config.json, tests/shpec/config/tls-terminate_shpec/config.json, tests/shpec/config/url-rewrite-full_shpec/config.json, tests/shpec/config/url-rewrite-prefix_shpec/config.json, tests/shpec/config/virtual-host_shpec/config.json
Adjust the filter configuration parameters of the test case.
=> Adjust the filter configuration parameters of the test case.

pjs/common/access-control.js, pjs/common/ratelimit.js, pjs/filter/header-modifier.js, pjs/filter/request-redirect.js, pjs/filter/url-rewrite.js, pjs/http/access-control-domain.js, pjs/http/access-control-route.js, tests/shpec/config/black-white-list_shpec/config.json, tests/shpec/config/circuit-breaker_shpec/config.json, tests/shpec/config/consumer-variables_shpec/config.json, tests/shpec/config/grpc-route_shpec/config.json, tests/shpec/config/header-modifier_shpec/config.json, tests/shpec/config/http-route_shpec/config.json, tests/shpec/config/https-passthrough_shpec/config.json, tests/shpec/config/load-balancing_shpec/config.json, tests/shpec/config/metrics-tracing-logging_shpec/config.json, tests/shpec/config/mtls-client_shpec/config.json, tests/shpec/config/mtls-upstream_shpec/config.json, tests/shpec/config/rate-limit_shpec/config.json, tests/shpec/config/request-redirect_shpec/config.json, tests/shpec/config/retry_shpec/config.json, tests/shpec/config/tcp-route_shpec/config.json, tests/shpec/config/throttle-domain_shpec/config.json, tests/shpec/config/throttle-route_shpec/config.json, tests/shpec/config/tls-sni_shpec/config.json, tests/shpec/config/tls-terminate_shpec/config.json, tests/shpec/config/url-rewrite-full_shpec/config.json, tests/shpec/config/url-rewrite-prefix_shpec/config.json, tests/shpec/config/virtual-host_shpec/config.json
Use camelcase and capital initials for naming configuration items
=> Use camelcase and capital initials for naming configuration items

docs/README.md, pjs/http/access-control-domain.js, pjs/http/access-control-route.js
Updated configuration documentation
=> Updated configuration documentation

pjs/http/proxy-redirect.js, pjs/samples/proxy-redirect/config.json
Added configuration "ProxyRedirect" for changing the "Location" and "Refresh" header fields of proxy server responses.
Context:	Configs, domain, route
=> Added configuration "ProxyRedirect" for changing the "Location" and "Refresh" header fields of proxy server responses.

pjs/config.json, pjs/http/proxy-redirect.js, pjs/server/web-server.js
For example：
"Gzip": {
"DisableGzip": false,
"GzipMinLength": 1024,
"GzipHttpVersion": 1.1,
"GzipTypes": [
"text/css",
"text/xml",
"text/html",
"text/plain",
"application/xhtml+xml",
"application/javascript"
],
"GzipDisable": "MSIE [1-6]\\."
}
=> Added "Gzip" configuration for compressing static html pages.

pjs/filter/url-rewrite.js
Allow setting empty path in url rewrite.
=> Allow setting empty path in url rewrite.

pjs/http/service.js, pjs/tcp/forward.js, pjs/tls/forward.js
Forwarding requests to upstream added "x-forwarded-for".
=> Forwarding requests to upstream added "x-forwarded-for".

pjs/config.json, pjs/filter/header-modifier.js, pjs/filter/url-rewrite.js, pjs/http/access-log.js, pjs/http/forward.js, tests/shpec/config/header-modifier_shpec/config.json
Context:	Configs、domain、route
For example:
"AccessLog": "/var/log/fgw-access.log",
"ProxyPreserveHost": true,
=> Added configuration "AccessLog", "ProxyPreserveHost".

pjs/filter/request-redirect.js, pjs/samples/request-redirect/config.json
example:
pjs/samples/request-redirect/config.json
=> Added usage example of filter "Request-Redirect".

pjs/filter/header-modifier.js, pjs/samples/header-modifier/config.json, pjs/samples/request-redirect/config.json, pjs/samples/url-rewrite/config.json
example:
pjs/samples/header-modifier/config.json
pjs/samples/url-rewrite/config.json
=> Added usage example of filter "header-modifier"、"url-rewrite".

pjs/common/health-check.js, pjs/lib/metrics.js
health check
change_status: Integer
Default：0，Normal to abnormal：-1， Abnormal to Normal：1
=> Added change_status to health check.

pjs/http/fault-injection.js, pjs/samples/fault-injection/config.json
for example:
"Fault": {
"Delay": {
"Percent": 50,
"Fixed": 300,
"Unit": "ms"
},
"Abort": {
"Percent": 50,
"Status": 503,
"Message": "fault-injection-message"
}
}
=> Added module "fault-injection.js" for injecting errors to test application resiliency.

pjs/http/forward.js, pjs/lib/connect-tls.js
for example:
"Endpoints": {
"www.flomesh.cn:443": {
"Weight": 50,
"Host": "www.flomesh.cn",
"UseSSL": true
},
"127.0.0.1:8081": {
"Weight": 50
}
}
=> Added configuration "Host", "UseSSL" for service endpoints.

tests/shpec/config/fault-injection_shpec/config.json, tests/shpec/config/per-connection-loadbalancing_shpec/config.json, tests/shpec/config/per-connection-loadbalancing_shpec/main.js, tests/shpec/config/per-request-loadbalancing_shpec/config.json, tests/shpec/config/per-request-loadbalancing_shpec/main.js, tests/shpec/pre_test.sh, tests/shpec/shell/fault-injection_shpec.sh, tests/shpec/shell/per-connection-loadbalancing_shpec.sh, tests/shpec/shell/per-request-loadbalancing_shpec.sh
=> Add shpec test case.

pjs/common/health-check.js, pjs/config.json, tests/shpec/config/cookie-sticky_shpec/config.json, tests/shpec/config/fault-injection_shpec/config.json, tests/shpec/config/health-check_shpec/config.json
for example:
"HealthCheck": {
"Interval": 10,
"MaxFails": 3,
"FailTimeout": 30,
"Path": "/",
"Matches": [
{
"StatusCodes": [
200
],
"Body": "<html>",
"Headers": {
"content-type": "text/html"
}
}
]
},
=> Modify the HealthCheck configuration format.
